# -*- coding: utf-8 -*-
"""wk8_art.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mFFS2r_sjnNqIUZ8rdY3iS2FC41Yj0OD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

art = pd.read_csv(
    'https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-12/artwork.csv'
    )

# code for the viz we are recreating
# x1 = np.array([-1, 1, 1, -1, -1], dtype='float')
# y1 = np.array([-1, -1, 1, 1, -1], dtype='float')

# plt.figure(figsize=(6,6))
# plt.xlim((-5000,5000))
# plt.ylim((-5000,5000))

# for i in range(len(art)):
#     plt.plot(x1*art['width'][i], y1*art['height'][i],'k',alpha=0.1)

# my take on it the example
fig, ax = plt.subplots(figsize=(6,6))

for i,j in zip(art.width,art.height):
  mid_w = i/2
  mid_h = j/2

  plt.xlim((-3000,3000))
  plt.ylim((-3000,3000))

  ax.add_patch(Rectangle((0-mid_w, 0-mid_h), i, j,
              edgecolor = 'black',
              fill=False,
              lw=0.5,
              alpha=0.1))
  


for i in ['left','right','bottom','top']:
  ax.spines[i].set_visible(False)

ax.set_xticks([])
ax.set_yticks([])

# plt.savefig('wk8_frames.png', dpi=300, bbox_inches='tight')