# -*- coding: utf-8 -*-
"""wk2_viz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nRKpF8h0Jvl9Na1XSqjZGK911CEtI7cF
"""

import pandas as pd

import requests
from PIL import Image
from io import BytesIO
import matplotlib as mpl
import matplotlib.pyplot as plt
from highlight_text import fig_text
import matplotlib.font_manager as fm
from matplotlib.patches import Circle
import matplotlib.patheffects as path_effects

!wget http://www.fontsaddict.com/fontface/roboto-bold.ttf

mpl.rc('font', family='Roboto')

df = pd.read_csv('athlete_events.csv')

df = pd.get_dummies(df, columns=['Medal'])

gc = (df
      .groupby(['Games','NOC','Event'])[['Medal_Gold']]
      .max()
      .reset_index()
      .groupby(['Games','NOC'])[['Medal_Gold']]
      .sum()
      .reset_index()
      )

sc = (df
      .groupby(['Games','NOC','Event'])[['Medal_Silver']]
      .max()
      .reset_index()
      .groupby(['Games','NOC'])[['Medal_Silver']]
      .sum()
      .reset_index()
      )

bc = (df
      .groupby(['Games','NOC','Event'])[['Medal_Bronze']]
      .max()
      .reset_index()
      .groupby(['Games','NOC'])[['Medal_Bronze']]
      .sum()
      .reset_index()
      )

medals = pd.merge(gc,sc,on=['NOC','Games']).merge(bc, on=['NOC','Games'])

viz = medals.loc[medals.NOC=='USA'].tail(5).reset_index(drop=True)

viz

fig = plt.gcf()
fig.set_facecolor("#f9f9f9")

colors = ['#FEE101', '#D7D7D7', '#A77044']

summer8 = fig.add_axes([0.54, 0.5, 0.75, 0.75]) 
summer8.pie(viz.iloc[0,2:], colors=colors, pctdistance=0.70,wedgeprops={'width':0.1})

logo8 = fig.add_axes([0.75,0.7,0.35,0.35])
logo8.axis("off")
url8 = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Ficons.iconarchive.com%2Ficons%2Fturbomilk%2Fbeijing-2008%2F256%2Fbeijing-2008-icon.png&f=1&nofb=1"
response8 = requests.get(url8)
img8 = Image.open(BytesIO(response8.content))
logo8.imshow(img8)

winter10 = fig.add_axes([0.95, 0.5, 0.75, 0.75]) 
winter10.pie(viz.iloc[1,2:], colors=colors, pctdistance=0.70,wedgeprops={'width':0.1})

logo10 = fig.add_axes([1.15,0.7,0.35,0.35])
logo10.axis("off")
url10 = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Flogonews.fr%2Fwp-content%2Fuploads%2F2014%2F02%2F2010_Vancouver_Winter_Olympics_logo.png&f=1&nofb=1"
response10 = requests.get(url10)
img10 = Image.open(BytesIO(response10.content))
logo10.imshow(img10)

summer12 = fig.add_axes([1.36, 0.5, 0.75, 0.75]) 
summer12.pie(viz.iloc[2,2:], colors=colors, pctdistance=0.70,wedgeprops={'width':0.1})

logo12 = fig.add_axes([1.57,0.7,0.35,0.35])
logo12.axis("off")
url12 = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcolorlib.com%2Fwp%2Fwp-content%2Fuploads%2Fsites%2F2%2F2014%2F02%2F2012-london-olympics-logo.png&f=1&nofb=1"
response12 = requests.get(url12)
img12 = Image.open(BytesIO(response12.content))
logo12.imshow(img12)

winter14 = fig.add_axes([.74, 0.093, 0.75, 0.75]) 
winter14.pie(viz.iloc[3,2:], colors=colors, pctdistance=0.75,wedgeprops={'width':0.1})

logo14 = fig.add_axes([.96,0.3,0.3,0.3])
logo14.axis("off")
url14 = "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fincitrio.com%2Fwp-content%2Fuploads%2F2014%2F02%2FSochi_logo_for_the_2014_Winter_Olympics.png&f=1&nofb=1"
response14 = requests.get(url14)
img14 = Image.open(BytesIO(response14.content))
logo14.imshow(img14)

summer16 = fig.add_axes([1.16, 0.09, 0.75, 0.75]) 
summer16.pie(viz.iloc[4,2:], colors=colors, pctdistance=0.70,wedgeprops={'width':0.1})

logo16 = fig.add_axes([1.36,0.3,0.35,0.35])
logo16.axis("off")
url16 = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.freebiesupply.com%2Flogos%2Flarge%2F2x%2Frio-2016-logo-png-transparent.png&f=1&nofb=1"
response16 = requests.get(url16)
img16 = Image.open(BytesIO(response16.content))
logo16.imshow(img16)

path_texts = []

path_texts.append(
    plt.figtext(1.1,1.1,"36",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#FEE101")
 )

path_texts.append(
    plt.figtext(.78,1.1,"39",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#D7D7D7")
 )

path_texts.append(
    plt.figtext(.83,.53,"35",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#A77044")
 )

path_texts.append(
    plt.figtext(1.48,1.1,"9",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#FEE101")
 )

path_texts.append(
    plt.figtext(1.197,1.1,"15",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#D7D7D7")
 )

path_texts.append(
    plt.figtext(1.35,.61,"13",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#A77044")
 )

path_texts.append(
    plt.figtext(1.915,1.1,"46",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#FEE101")
 )

path_texts.append(
    plt.figtext(1.6075,.86,"28",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#D7D7D7")
 )

path_texts.append(
    plt.figtext(1.915,.6,"29",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#A77044")
 )

path_texts.append(
    plt.figtext(1.13,.67,"9",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#FEE101")
 )

path_texts.append(
    plt.figtext(.91,.41,"7",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#D7D7D7")
 )

path_texts.append(
    plt.figtext(1.05,.122,"12",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#A77044")
 )

path_texts.append(
    plt.figtext(1.55,.67,"46",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#FEE101")
 )

path_texts.append(
    plt.figtext(1.39,.2,"37",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#D7D7D7")
 )

path_texts.append(
    plt.figtext(1.72,.2,"38",
        fontweight="bold",
        fontsize=12,
        fontfamily="Roboto",
        va="bottom",
        ha="right",
        color="#A77044")
 )

(plt
 .figtext(1.35,
          1.4,
          'Who Said Pie Charts Are Bad?',
          va='center',
          ha='center',
          fontsize=28,
          fontfamily="Roboto",
          color='#30302f')
 )
(plt
 .figtext(1.35,
          1.275,
          "USA's Medal Distribution Over the Last 5 Olympics",
          va='center',
          ha='center',
          fontsize=18,
          fontfamily="Roboto",
          color='#30302f')
 )

(plt
 .figtext(1.325,
          .03,
          "Data: Kaggle | Figure: Max Bolger",
          va='center',
          ha='center',
          fontsize=12,
          fontfamily="Roboto")
 )

for t in path_texts:
    t.set_path_effects([path_effects.withStroke(linewidth=2,foreground="black")])

plt.savefig('wk2_viz.png',dpi=300,bbox_inches='tight')
